POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Michael Nguyen",
    "number": "0099008819"
}

###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "",
    "number": ""
}

# {
#     "name": "Liisa Marttinen",
#     "number": "040-243563"
# }