GET http://localhost:3000/api/diaries
###
POST http://localhost:3000/api/diaries
content-type: application/json

{
  "comment": "test",
  "date": "2023-2-7",
  "weather": "sun",
  "visibility": "great"
}